'use strict';
/**
 * credit-card router — default CRUD routes generated by the core factory.
 */
const { createCoreRouter } = require('@strapi/strapi').factories;
module.exports = createCoreRouter('api::credit-card.credit-card');
