'use strict';
/**
 * company router — default CRUD routes generated by the core factory.
 */
const { createCoreRouter } = require('@strapi/strapi').factories;
module.exports = createCoreRouter('api::company.company');
