'use strict';
/**
 * testimonial router — default CRUD routes generated by the core factory.
 */
const { createCoreRouter } = require('@strapi/strapi').factories;
module.exports = createCoreRouter('api::testimonial.testimonial');
